/**
 * IMX generator entry point.
 * Keep this module UI-free so it can later move to a backend service.
 */
export function generateIMX({ tables, siteId, options = {} }) {
  const warnings = [];

  if (!siteId || !siteId.toString().trim()) {
    throw new Error("Missing siteId.");
  }
  const sid = siteId.toString().trim();

  const rack = tables["ITKRackLayout"]?.records;
  const io = tables["ITKIOPoint"]?.records;

  if (!Array.isArray(rack) || rack.length === 0) {
    throw new Error("ITKRackLayout table is missing or empty.");
  }
  if (!Array.isArray(io) || io.length === 0) {
    warnings.push("ITKIOPoint is missing or empty (continuing).");
  }

  // Filter down to site rows (Phase 0: simple equality match)
  const siteCol = options.siteIdColumn || "Site_ID";
  const rackForSite = rack.filter(r => (r[siteCol] ?? "").toString().trim() === sid);
  const ioForSite = (io || []).filter(r => (r[siteCol] ?? "").toString().trim() === sid);

  if (rackForSite.length === 0) {
    warnings.push(`No ITKRackLayout rows matched ${siteCol} = ${sid}.`);
  }
  if (ioForSite.length === 0) {
    warnings.push(`No ITKIOPoint rows matched ${siteCol} = ${sid}.`);
  }

  // TODO: Replace this placeholder with real IMX generation logic from VBA.
  // For now we emit a deterministic stub so the UI flow works end-to-end.
  const lines = [];
  lines.push("; IMX (placeholder) generated by in-browser generator");
  lines.push(`; Site_ID: ${sid}`);
  lines.push(`; Rack rows: ${rackForSite.length} / ${rack.length}`);
  lines.push(`; IO rows: ${ioForSite.length} / ${(io || []).length}`);
  lines.push(`; GeneratedAt: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("; Next step: implement the real IMX structure here.");
  lines.push("; Keep parsing/lookup logic inside this module so it can move server-side later.");

  return { imxText: lines.join("\n"), warnings, stats: { rackForSite: rackForSite.length, ioForSite: ioForSite.length } };
}
